name: Multiple repos clone tests

on:
  push:
    branches:
      - main
jobs:
  multi-repos:
    runs-on: ubuntu-latest
    env:
      MAIN_DIR: main
      ANOTHER_DIR: another
    steps:
      - run: |
          pwd
          ls -la
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.MAIN_DIR }}
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: bioerrorlog/blockchain_in_rust
          path: ${{ env.ANOTHER_DIR }}
      - run: |
          pwd
          ls -la
      - name: Check the main repo
        working-directory: ${{ env.MAIN_DIR }}
        run: |
          pwd
          ls -la
      - name: Check the another repo
        working-directory: ${{ env.ANOTHER_DIR }}
        run: |
          pwd
          ls -la
      - run: |
          pwd
          ls -la
